name: mlst
## TODO nf-core: Add a description of the module and list keywords
description: Run Torsten Seemann's classic MLST on a genome assembly
keywords:
  - sort
tools:
  - mlst:
      ## TODO nf-core: Add a description and other details for the software below
      description: Scan contig files against PubMLST typing schemes
      homepage: None
      documentation: None
      tool_dev_url: None
      doi: ""
      licence: ['GPL v2']

## TODO nf-core: Add a description of all of the variables used as input
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  ## TODO nf-core: Delete / customise this example input
  - fasta:
      type: file
      description: Assembly fasta file
      pattern: "*.{fasta,fa,fna}"

## TODO nf-core: Add a description of all of the variables used as output
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - version:
      type: file
      description: File containing software version
      pattern: "*.{version.txt}"
  ## TODO nf-core: Delete / customise this example output
  - bam:
      type: file
      description: MLST calls in tsv format
      pattern: "*.{tsv}"

authors:
  - "@lskatz"
  - "@tseemann"
